import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const rail = Raleway({
  subsets: ["latin"],
  variable: "--font-rail",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${rail.className}`}>{children}</body>
    </html>
  );
}
